server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: RecipeBookApp

  datasource:
    url: jdbc:postgresql://localhost:5432/nutrition_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000

  # ? JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: update          # ???????/????????? ??????? ?????????????. ??? ?????????? ??????????? validate
    show-sql: true              # ????? SQL-???????? ? ???????
    properties:
      hibernate:
        format_sql: true        # ???????? ?????????????? SQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false         # Best practice: ????????? OSIV ??? ????????? N+1 ? ?????? ??????????

  # ? ?????????????? ??? ? JSON
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# ? ???????????
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.nutrition: DEBUG

file:
  upload-dir: ./uploads # Директория относительно корня проекта